## remap leader key
unbind C-b

set-option -g prefix C-a

## add config reload keymap
unbind r

bind r source-file ~/.tmux.conf

## General settings
set -sg escape-time 0
set -g mouse on
set-option -g status-position top
set-option -g renumber-windows on
set-option -g allow-rename off

## Vim motion in tmux using prefix
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind %
unbind '"'

bind-key | split-pane -h
bind-key - split-pane -v

## List of plugins
## General plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

## Productivity plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

## Theme and Colorscheme plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-battery'


## Catppuccin Theme Configuration
set -g @catppuccin_flavour 'mocha'

set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session date_time battery"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"

## Tmux Resurrect Configuration
set -g @resurrect-strategy-nvim 'session'

## Tmux Continuum Configuration
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'

