## remap leader key
unbind C-b

set-option -g prefix C-a

## add config reload keymap
unbind r

bind r source-file ~/.tmux.conf

## General settings
set -sg escape-time 0
set -g mouse on
set-option -g status-position top
set-option -g renumber-windows on
set-option -g allow-rename off
set -s set-clipboard on
set -s set-clipboard external
set -s set-clipboard off
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

## Vim motion in tmux using prefix
unbind %
unbind '"'
unbind c

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key | split-pane -h -c "#{pane_current_path}"
bind-key - split-pane -v -c "#{pane_current_path}"
bind-key c new-window -c "$HOME/workspace"

## List of plugins
## General plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

## Productivity plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

## Theme and Colorscheme plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-battery'


## Catppuccin Theme Configuration
set -g @catppuccin_flavour 'mocha'

set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session date_time battery"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"

## Tmux Resurrect Configuration
set -g @resurrect-strategy-nvim 'session'

## Tmux Continuum Configuration
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'

